name: github actions workflow
on: push
jobs:
  actions-demo:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout stage
        uses: actions/checkout@v4
      - name: print index.html
        run: cat index.html
