name: env demo
on: workflow_dispatch
env:
  TEST_ENV: " dev "
jobs:
  env-demo:
    env:
      TEST_ENV: " test "
    runs-on: ubuntu-latest
    steps:
      - name: connecting to env
        env:
          TEST_ENV: " PROD "
        run: echo " welcome to $TEST_ENV "
